/**
 * Board data representation
 * Array of arrays where each subarray represents one row
 * -1 = white stone, 0 = empty, 1 = black stone
 */
export type SignMap = number[][];

/**
 * Vertex coordinate [x, y]
 * [0, 0] is top-left position
 */
export type Vertex = [number, number];

/**
 * Sign value: -1 (white), 0 (empty), or 1 (black)
 */
export type Sign = -1 | 0 | 1;

/**
 * Options for the guess function
 */
export interface GuessOptions {
  /**
   * If true, assumes player areas are completely surrounded (better results)
   * @default false
   */
  finished?: boolean;

  /**
   * Number of random playthroughs to make
   * @default 100
   */
  iterations?: number;
}

/**
 * WASM module interface (generated by wasm-pack)
 */
export interface DeadstonesWasm {
  guess(
    data: Int8Array,
    width: number,
    finished: boolean,
    iterations: number,
    seed: number
  ): Uint32Array;
  getProbabilityMap(data: Int8Array, width: number, iterations: number, seed: number): Float32Array;
  playTillEnd(data: Int8Array, width: number, sign: number, seed: number): Int8Array;
  getFloatingStones(data: Int8Array, width: number): Uint32Array;
}
