/**
 * Type declarations for WASM module generated by wasm-pack
 * This file allows TypeScript to compile before WASM is built
 */

declare module '../../wasm/deadstones' {
  export function guess(
    data: Int8Array,
    width: number,
    finished: boolean,
    iterations: number,
    seed: number,
  ): Uint32Array;

  export function getProbabilityMap(
    data: Int8Array,
    width: number,
    iterations: number,
    seed: number,
  ): Float32Array;

  export function playTillEnd(
    data: Int8Array,
    width: number,
    sign: number,
    seed: number,
  ): Int8Array;

  export function getFloatingStones(data: Int8Array, width: number): Uint32Array;
}
